name: car_loan_app
description: Car Loan Analyzer App
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.0
  file_picker: ^10.3.8

  cupertino_icons: ^1.0.6

flutter:
  uses-material-design: true
